// This file was generated by ecm_setup_version(): DO NOT EDIT!

#ifndef MAIA_VERSION_H
#define MAIA_VERSION_H

#define MAIA_VERSION_STRING "0.1.0"
#define MAIA_VERSION_MAJOR 0
#define MAIA_VERSION_MINOR 1
#define MAIA_VERSION_PATCH 0
#define MAIA_VERSION ((0<<16)|(1<<8)|(0))

#endif
